### ISSUE TITLE
Put project logos on the Documentation page

### ISSUE THREAD

**Issue by bmorcos** [nengo/nengo.github.io#61]
Currently only Nengo, NengoDL, and NengoSPA are using the graphic logos. I guess we wait until we merge nengo/design#7?

Do we want the images to be webhosted (like the three are currently) or just drop these in` _static`?

**Comment by bmorcos** [comment]
Also wondering two more things:

- Do we want to organize this table the same way as the drop down menu?
- Do we want to make logos for all the links here? I think it looks strange mixing the large logos and small text.

**Comment by drasmuss** [comment]
I would organize the table the same way as the dropdown, and use text for everything (no logos).  I don't think we want to force every project we list here to have a Nengo-themed logo, and if we aren't enforcing that then I think it looks better to just have everything as text rather than mixing, as you say.
